# Dependencies
highlighter:      rouge
plugins_dir:      [jekyll-paginate, redcarpet, jekyll-gist]

# Permalinks
permalink:        pretty

# Setup
title:            kaborso
tagline:          'akil brooks'
description:      'web development and media production'
url:              http://kaborso.com
baseurl:          /

author:
  name:           'Akil Brooks'

links:
    - title:      open source work
      url:        https://github.com/kaborso/
    - title:      tinkering
      url:        '/tinkering'
    - title:      interactive things
      url:        https://tilde.town/~kaborso/
    - title:      objects for sale
      url:        https://kaborso.itch.io
    - title:      code thoughts
      url:        '/posts'
    - title:      film thoughts
      url:        http://seneschalofdust.com
    - title:      video stuff
      url:        '#'
